arenas:
  example-arena:
    x1: 0
    y1: 0
    z1: 0
    x2: 0
    y2: 0
    y3: 0
    redSpawnX: 0
    redSpawnY: 0
    redSpawnZ: 0
    blueSpawnX: 0
    blueSpawnY: 0
    blueSpawnZ: 0
    world: world

messages:
  game-beginning-msg: "A game of &aMagma &fis starting at &b${arena_name}&f. Do &b/mgm join ${arena_name} &fto play!"