name: magma
main: net.rocketeer.magma.MagmaPlugin
version: 0.0.1
depend: [Vault]
commands:
    mgm:
        description: Base command for all Magma-related things.
        usage: /mgm
        permission: magma.cmd
        permission-message: No permission.
